# 1.Print 'Hello HCIA'.

In [1]:
print("Hello HCIA")

Hello HCIA


In [2]:
import sklearn

In [3]:
#print(sklearn.__version__)

# 2.Define two variables and calculate their sum.

In [4]:
a=1

In [5]:
b=3

In [6]:
c=a+b

In [7]:
c

4

# 3.Define a list and replicate in three different ways.

In [8]:
list1 = [1,2]

In [9]:
list2 = list([1,2])

In [10]:
#list3 = (1,2)

In [30]:
list3 = [] 
list3.append(1) 
list3.append(2) 

# 4.Define two lists and merge them together.

In [11]:
listone = [1, 2, 3]
listtwo = [4, 5, 6]
mergedlist = listone + listtwo[0:1000]
print(mergedlist)

[1, 2, 3, 4, 5, 6]


# 5. Get the last element of the list and print it.

In [12]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a[len(a)-1]

10

# 6.Define a tuple that contains only one element.

In [13]:
t=(1)
print(t)

1


# 7.Define a three-line long string.

In [31]:
long_string = '''
three-line 
long
tamsi
'''
print(long_string)


three-line 
long
tamsi



# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [15]:
t=(1,2,3)
for item in t:
    print(item)


1
2
3


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [16]:
def Mul(num1, num2):
    answer = num1 * num2
    return answer

print(Mul(8, 6))

48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [17]:
import numpy as np

In [18]:
mat = np.array([[0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0]])


In [19]:
print(mat.shape)

(5, 5)


In [20]:
print(mat)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [21]:
import numpy as np

In [22]:
mat = np.array([[0, 0, 0, 0, 0,0],
                [0, 0, 0, 0, 0,0],
                [0, 0, 0, 0, 0,0],
                [0, 0, 0, 0, 0,0]])


In [23]:
print(mat.shape)

(4, 6)


In [24]:
print(mat)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [25]:
mat=np.arange(15)

In [26]:
mat.shape=(3,5)


In [27]:
print(mat.shape)

(3, 5)


In [28]:
print(mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [29]:
# Program to multiply two matrices using nested loops  

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]
